"""Add is_correct to question_options

Revision ID: 6eedf3dc5590
Revises: cbff7e2b46f7
Create Date: 2025-08-20 21:13:53.534250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eedf3dc5590'
down_revision: Union[str, Sequence[str], None] = 'cbff7e2b46f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_options', sa.Column('is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_options', 'is_correct')
    # ### end Alembic commands ###
