from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class GameCreateRequest(BaseModel):
  prompt: str
  hostname: str

@app.get("/")
def read_root():
    return {"Hello": "World"}

@app.get("/health")
def health_check():
    return {"status": "healthy",
            "Code": 200,
            "Message": "Service is running smoothly."}

@app.post("/game/create")
def create_game(game: GameCreateRequest):
  # TODO: Pass prompt to LLM to generate the game
  
  return {
    "status": "success",
    "message": "Game creation initiated",
    "game_id": "12345",  # This would be generated by the game creation logic
    "parameters": {
      "prompt": game.prompt,
      "hostname": game.hostname
    }
  }
